name = "bolao-brasileirao-api"
main = "src/index.ts"
compatibility_date = "2026-02-10"

[vars]
FOOTBALL_DATA_BASE_URL = "https://api.football-data.org/v4"
FOOTBALL_DATA_COMPETITION_ID = "2013"
DEFAULT_EXTERNAL_LINK = "https://g1.globo.com/futebol/brasileirao-serie-a/"
CORS_ORIGINS = "http://localhost:5173"
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "bolao-brasileirao"
database_id = "28b1c613-f137-4b15-afa9-ff3250025127"
migrations_dir = "migrations"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.routes]]
pattern = "*/admin/*"
zone_name = "bolao-brasileirao.pages.dev"
custom_domain = true
