name = "bolao-brasileirao-api"
main = "src/index.ts"
compatibility_date = "2026-02-10"

[vars]
FOOTBALL_DATA_BASE_URL = "https://api.football-data.org/v4"
FOOTBALL_DATA_COMPETITION_ID = "2013"
DEFAULT_EXTERNAL_LINK = "https://g1.globo.com/futebol/brasileirao-serie-a/"

[[d1_databases]]
binding = "DB"
database_name = "bolao-brasileirao"
database_id = ""
migrations_dir = "migrations"
